[package]
name = "libretto"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
pyproject-toml = "0.13.7"
serde = "1.0.228"
toml = "0.9.8"
rust-venv = { path = "../rust-venv" }